// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using employee_management_backend.Data;

#nullable disable

namespace employee_management_backend.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("employee_management_backend.Models.Domains.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1cda0f6-5495-46d3-a4de-1e7aee9de824"),
                            DepartmentName = "IT"
                        },
                        new
                        {
                            Id = new Guid("77426725-34bc-41b0-a6fd-f9c224be385f"),
                            DepartmentName = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("844798c6-811f-4b02-b2df-868c2d221970"),
                            DepartmentName = "HR"
                        },
                        new
                        {
                            Id = new Guid("bd4ba948-e562-4bd6-80ae-9fad4a96e11a"),
                            DepartmentName = "Management"
                        });
                });

            modelBuilder.Entity("employee_management_backend.Models.Domains.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("GenderTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GenderTypeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("employee_management_backend.Models.Domains.GenderType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GenderTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38a839e8-1b66-41c3-8435-c8ab8dd2a867"),
                            Gender = "Male"
                        },
                        new
                        {
                            Id = new Guid("a8f564e3-8cd4-403f-8832-5c035120e365"),
                            Gender = "Female"
                        },
                        new
                        {
                            Id = new Guid("174f432d-a1d5-4894-a3e6-b1465a54df81"),
                            Gender = "Other"
                        });
                });

            modelBuilder.Entity("employee_management_backend.Models.Domains.Employee", b =>
                {
                    b.HasOne("employee_management_backend.Models.Domains.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("employee_management_backend.Models.Domains.GenderType", "GenderType")
                        .WithMany()
                        .HasForeignKey("GenderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("GenderType");
                });
#pragma warning restore 612, 618
        }
    }
}
